uses: actions/checkout@v2
- name: Set up Docker Buildx
uses: docker/setup-buildx-action@v2
- name: Log in to container registry
uses: docker/login-action@v2
with:
registry: https://index.docker.io/v1/
username: ${{USERNAME
}}
password: ${{PASS
}}
- name: Build and push container image to registry
uses: docker/build-push-action@v3
uses: actions/checkout@v2
- name: Set up Docker Buildx
uses: docker/setup-buildx-action@v2
- name: Log in to container registry
uses: docker/login-action@v2
with:
registry: https://index.docker.io/v1/
username: ${{USERNAME
}}
password: ${{PASS
}}
- name: Build and push container image to registry
uses: docker/build-push-action@v3
